[package]
name = "sflow-collector"
version = "0.1.0"
authors = ["Andreas Rammhold <andreas@rammhold.de>"]

[dependencies]
sflow = {path="../rust-sflow"}
#//{ git = "https://github.com/JakDar/rust-sflow", branch = "feature/add-sampled-header-contents"}
